// datos-tabla.js - Base de datos completa para el Sistema IE San José
const periodicBlocks = [
  {
    id: "bloque1",
    file: "./targets/bloque1.mind",
    elements: {
      0: { symbol: "H", name: "Hidrógeno", group: "No Metal", desc: "Gas altamente inflamable, el elemento más ligero y abundante del universo.", model: "./models/1H.glb" },
      1: { symbol: "He", name: "Helio", group: "Gas Noble", desc: "Gas inerte, incoloro y el segundo elemento más ligero de la tabla.", model: "./models/2He.glb" },
      2: { symbol: "Li", name: "Litio", group: "Metal Alcalino", desc: "Metal blando, utilizado en la fabricación de baterías recargables.", model: "./models/3Li.glb" },
      3: { symbol: "Be", name: "Berilio", group: "Metal Alcalinotérreo", desc: "Metal raro, ligero y quebradizo, usado en aleaciones de alta resistencia.", model: "./models/4Be.glb" },
      4: { symbol: "B", name: "Boro", group: "Metaloide", desc: "Semiconductor utilizado en la fabricación de vidrio de borosilicato.", model: "./models/5B.glb" },
      5: { symbol: "C", name: "Carbono", group: "No Metal", desc: "Base fundamental de la química orgánica y de la vida en la Tierra.", model: "./models/6C.glb" },
      6: { symbol: "N", name: "Nitrógeno", group: "No Metal", desc: "Gas que constituye aproximadamente el 78% de la atmósfera terrestre.", model: "./models/7N.glb" },
      7: { symbol: "O", name: "Oxígeno", group: "No Metal", desc: "Gas esencial para la respiración celular y la vida en el planeta.", model: "./models/8O.glb" },
      8: { symbol: "F", name: "Flúor", group: "Halógeno", desc: "El elemento más reactivo y electronegativo de todos.", model: "./models/9F.glb" },
      9: { symbol: "Ne", name: "Neón", group: "Gas Noble", desc: "Gas inerte que emite un brillo rojizo brillante al ser ionizado.", model: "./models/10Ne.glb" },
      10: { symbol: "Na", name: "Sodio", group: "Metal Alcalino", desc: "Metal blando muy reactivo, componente esencial de la sal común.", model: "./models/11Na.glb" },
      11: { symbol: "Mg", name: "Magnesio", group: "Metal Alcalinotérreo", desc: "Metal ligero e indispensable para los tejidos vivos y la fotosíntesis.", model: "./models/12Mg.glb" },
      12: { symbol: "Al", name: "Aluminio", group: "Metal del bloque p", desc: "Metal ligero, no ferromagnético y de alta resistencia a la corrosión.", model: "./models/13Al.glb" },
      13: { symbol: "Si", name: "Silicio", group: "Metaloide", desc: "Semiconductor primordial en la fabricación de microchips y electrónica.", model: "./models/14Si.glb" },
      14: { symbol: "P", name: "Fósforo", group: "No Metal", desc: "Elemento altamente reactivo, esencial para la transferencia de energía celular (ATP).", model: "./models/15P.glb" },
      15: { symbol: "S", name: "Azufre", group: "No Metal", desc: "No metal de color amarillo pálido con un olor característico al quemarse.", model: "./models/16S.glb" },
      16: { symbol: "Cl", name: "Cloro", group: "Halógeno", desc: "Gas amarillo-verdoso utilizado para la purificación de agua.", model: "./models/17Cl.glb" },
      17: { symbol: "Ar", name: "Argón", group: "Gas Noble", desc: "Tercer gas más común en la atmósfera, usado en iluminación.", model: "./models/18Ar.glb" },
      18: { symbol: "K", name: "Potasio", group: "Metal Alcalino", desc: "Metal alcalino esencial para la función osmótica y nerviosa.", model: "./models/19K.glb" },
      19: { symbol: "Ca", name: "Calcio", group: "Metal Alcalinotérreo", desc: "Metal esencial para la estructura ósea de los organismos vivos.", model: "./models/20Ca.glb" },
      20: { symbol: "Sc", name: "Escandio", group: "Metal de Transición", desc: "Metal de transición ligero utilizado en aleaciones aeroespaciales.", model: "./models/21Sc.glb" },
      21: { symbol: "Ti", name: "Titanio", group: "Metal de Transición", desc: "Metal de gran resistencia, baja densidad y excelente biocompatibilidad.", model: "./models/22Ti.glb" },
      22: { symbol: "V", name: "Vanadio", group: "Metal de Transición", desc: "Metal de transición duro utilizado en aditivos de acero estructural.", model: "./models/23V.glb" },
      23: { symbol: "Cr", name: "Cromo", group: "Metal de Transición", desc: "Metal resistente a la corrosión, clave para el acero inoxidable.", model: "./models/24Cr.glb" },
      24: { symbol: "Mn", name: "Manganeso", group: "Metal de Transición", desc: "Elemento esencial para la siderurgia y la producción de aleaciones.", model: "./models/25Mn.glb" },
      25: { symbol: "Fe", name: "Hierro", group: "Metal de Transición", desc: "El metal de transición más común en la Tierra, núcleo del planeta.", model: "./models/26Fe.glb" },
      26: { symbol: "Co", name: "Cobalto", group: "Metal de Transición", desc: "Metal ferromagnético empleado en imanes y baterías de alta potencia.", model: "./models/27Co.glb" },
      27: { symbol: "Ni", name: "Níquel", group: "Metal de Transición", desc: "Metal blanco plateado muy resistente a la oxidación atmosférica.", model: "./models/28Ni.glb" },
      28: { symbol: "Cu", name: "Cobre", group: "Metal de Transición", desc: "Excelente conductor eléctrico y térmico, clave en telecomunicaciones.", model: "./models/29Cu.glb" },
      29: { symbol: "Zn", name: "Zinc", group: "Metal de Transición", desc: "Metal utilizado principalmente en el galvanizado del hierro.", model: "./models/30Zn.glb" },
      30: { symbol: "Ga", name: "Galio", group: "Metal del bloque p", desc: "Metal que se derrite a temperatura ambiente en la mano.", model: "./models/31Ga.glb" },
      31: { symbol: "Ge", name: "Germanio", group: "Metaloide", desc: "Semiconductor utilizado en sistemas ópticos infrarrojos.", model: "./models/32Ge.glb" },
      32: { symbol: "As", name: "Arsénico", group: "Metaloide", desc: "Metaloide famoso por su alta toxicidad y aplicaciones en semiconductores.", model: "./models/33As.glb" },
      33: { symbol: "Se", name: "Selenio", group: "No Metal", desc: "Utilizado en la fabricación de vidrio y células fotovoltaicas.", model: "./models/34Se.glb" },
      34: { symbol: "Br", name: "Bromo", group: "Halógeno", desc: "Único no metal que se encuentra en estado líquido a temperatura ambiente.", model: "./models/35Br.glb" },
      35: { symbol: "Kr", name: "Kriptón", group: "Gas Noble", desc: "Gas noble utilizado en luces de alta intensidad y fotografía.", model: "./models/36Kr.glb" },
      36: { symbol: "Rb", name: "Rubidio", group: "Metal Alcalino", desc: "Metal alcalino altamente reactivo, usado en relojes atómicos.", model: "./models/37Rb.glb" },
      37: { symbol: "Sr", name: "Estroncio", group: "Metal Alcalinotérreo", desc: "Metal alcalinotérreo que imparte un color rojo brillante a la pirotecnia.", model: "./models/38Sr.glb" },
      38: { symbol: "Y", name: "Itrio", group: "Metal de Transición", desc: "Metal de transición empleado en fósforos para pantallas de TV antiguas.", model: "./models/39Y.glb" },
      39: { symbol: "Zr", name: "Circonio", group: "Metal de Transición", desc: "Metal muy resistente al calor y la corrosión, usado en reactores nucleares.", model: "./models/40Zr.glb" }
    }
  },
  {
    id: "bloque2",
    file: "./targets/bloque2.mind",
    elements: {
      0: { symbol: "Nb", name: "Niobio", group: "Metal de Transición", desc: "Metal dúctil utilizado en superaleaciones aeroespaciales.", model: "./models/41Nb.glb" },
      1: { symbol: "Mo", name: "Molibdeno", group: "Metal de Transición", desc: "Metal con uno de los puntos de fusión más altos en estado puro.", model: "./models/42Mo.glb" },
      2: { symbol: "Tc", name: "Tecnecio", group: "Metal de Transición", desc: "Primer elemento obtenido de forma artificial, usado en medicina nuclear.", model: "./models/43Tc.glb" },
      3: { symbol: "Ru", name: "Rutenio", group: "Metal de Transición", desc: "Metal raro usado en contactos eléctricos y catalizadores industriales.", model: "./models/44Ru.glb" },
      4: { symbol: "Rh", name: "Rodio", group: "Metal de Transición", desc: "Metal extremadamente precioso usado en catalizadores vehiculares.", model: "./models/45Rh.glb" },
      5: { symbol: "Pd", name: "Paladio", group: "Metal de Transición", desc: "Metal capaz de absorber grandes volúmenes de gas hidrógeno.", model: "./models/46Pd.glb" },
      6: { symbol: "Ag", name: "Plata", group: "Metal de Transición", desc: "El elemento con la mayor conductividad eléctrica conocida.", model: "./models/47Ag.glb" },
      7: { symbol: "Cd", name: "Cadmio", group: "Metal de Transición", desc: "Metal tóxico empleado antiguamente en acumuladores recargables.", model: "./models/48Cd.glb" },
      8: { symbol: "In", name: "Indio", group: "Metal del bloque p", desc: "Metal blando clave para las pantallas táctiles de cristal líquido (ITO).", model: "./models/49In.glb" },
      9: { symbol: "Sn", name: "Estaño", group: "Metal del bloque p", desc: "Metal maleable resistente a la corrosión, usado para soldaduras blandas.", model: "./models/50Sn.glb" },
      10: { symbol: "Sb", name: "Antimonio", group: "Metaloide", desc: "Metaloide utilizado principalmente en aleaciones para endurecer el plomo.", model: "./models/51Sb.glb" },
      11: { symbol: "Te", name: "Telurio", group: "Metaloide", desc: "Elemento raro utilizado en paneles solares y metalurgia de aleación.", model: "./models/52Te.glb" },
      12: { symbol: "I", name: "Yodo", group: "Halógeno", desc: "No metal azul-negruzco indispensable para el funcionamiento de la tiroides.", model: "./models/53I.glb" },
      13: { symbol: "Xe", name: "Xenón", group: "Gas Noble", desc: "Gas noble pesado que emite una luz azulada en faros de alta potencia.", model: "./models/54Xe.glb" },
      14: { symbol: "Cs", name: "Cesio", group: "Metal Alcalino", desc: "El metal más reactivo del grupo alcalino, define el segundo exacto.", model: "./models/55Cs.glb" },
      15: { symbol: "Ba", name: "Bario", group: "Metal Alcalinotérreo", desc: "Compuestos de bario se utilizan como medio de contraste en radiografías.", model: "./models/56Ba.png" },
      16: { symbol: "La", name: "Lantano", group: "Lantánido", desc: "Elemento base de la serie de tierras raras, usado en lentes ópticos.", model: "./models/57La.glb" },
      17: { symbol: "Ce", name: "Cerio", group: "Lantánido", desc: "El lantánido más abundante, componente de las piedras de encendedor.", model: "./models/58Ce.glb" },
      18: { symbol: "Pr", name: "Praseodimio", group: "Lantánido", desc: "Tierras raras que confieren un color verde puro a vidrios ópticos.", model: "./models/59Pr.glb" },
      19: { symbol: "Nd", name: "Neodinio", group: "Lantánido", desc: "Crucial para la fabricación de los imanes permanentes más potentes del mundo.", model: "./models/60Nd.glb" },
      20: { symbol: "Pm", name: "Prometio", group: "Lantánido", desc: "Elemento radiactivo sintético utilizado en pinturas luminiscentes espaciales.", model: "./models/61Pm.glb" },
      21: { symbol: "Sm", name: "Samario", group: "Lantánido", desc: "Utilizado en imanes estables a altas temperaturas y medicina oncológica.", model: "./models/62Sm.glb" },
      22: { symbol: "Eu", group: "Lantánido", name: "Europio", desc: "El más reactivo de los lantánidos, genera la luminiscencia roja en pantallas.", model: "./models/63Eu.glb" },
      23: { symbol: "Gd", name: "Gadolinio", group: "Lantánido", desc: "Metal de tierras raras utilizado como agente de contraste en resonancias.", model: "./models/64Gd.glb" },
      24: { symbol: "Tb", name: "Terbio", group: "Lantánido", desc: "Tierra rara dopante en dispositivos de estado sólido y pantallas verdes.", model: "./models/65Tb.glb" },
      25: { symbol: "Dy", name: "Disprosio", group: "Lantánido", desc: "Metal con alta susceptibilidad magnética, usado en reactores nucleares.", model: "./models/66Dy.glb" },
      26: { symbol: "Ho", name: "Holmio", group: "Lantánido", desc: "Posee propiedades magnéticas extremas, usado en láseres médicos.", model: "./models/67Ho.glb" },
      27: { symbol: "Er", name: "Erbio", group: "Lantánido", desc: "Iones de erbio se usan como amplificadores en cables de fibra óptica.", model: "./models/68Er.glb" },
      28: { symbol: "Tm", name: "Tulio", group: "Lantánido", desc: "El lantánido menos abundante, fuente de rayos X portátiles.", model: "./models/69Tm.glb" },
      29: { symbol: "Yb", name: "Iterbio", group: "Lantánido", desc: "Metal empleado en la mejora de aceros inoxidables y relojes atómicos.", model: "./models/70Yb.glb" },
      30: { symbol: "Lu", name: "Lutecio", group: "Lantánido", desc: "El lantánido más denso y duro, usado en tomografía por emisión de positrones.", model: "./models/71Lu.glb" },
      31: { symbol: "Hf", name: "Hafnio", group: "Metal de Transición", desc: "Metal con gran capacidad de absorción de neutrones térmicos.", model: "./models/72Hf.glb" },
      32: { symbol: "Ta", name: "Tantalio", group: "Metal de Transición", desc: "Metal refractario de alta resistencia al ataque químico, clave en capacitores.", model: "./models/73Ta.glb" },
      33: { symbol: "W", name: "Wolframio", group: "Metal de Transición", desc: "Metal con el punto de fusión más alto de la tabla, filamento de focos.", model: "./models/74W.glb" },
      34: { symbol: "Re", name: "Renio", group: "Metal de Transición", desc: "Metal denso usado en superaleaciones para turbinas de aviones a reacción.", model: "./models/75Re.glb" },
      35: { symbol: "Os", name: "Osmio", group: "Metal de Transición", desc: "El elemento natural más denso y pesado de la Tierra.", model: "./models/76Os.glb" },
      36: { symbol: "Ir", name: "Iridio", group: "Metal de Transición", desc: "El segundo elemento más denso y el más resistente a la corrosión.", model: "./models/77Ir.glb" },
      37: { symbol: "Pt", name: "Platino", group: "Metal de Transición", desc: "Metal precioso noble muy noble, de alta joyería y catálisis médica.", model: "./models/78Pt.glb" },
      38: { symbol: "Au", name: "Oro", group: "Metal de Transición", desc: "Metal precioso inalterable, símbolo histórico de valor y gran conductor.", model: "./models/79Au.glb" },
      39: { symbol: "Hg", name: "Mercurio", group: "Metal de Transición", desc: "Único metal que se mantiene en estado líquido a temperatura ambiente.", model: "./models/80Hg.glb" }
    }
  },
  {
    id: "bloque3",
    file: "./targets/bloque3.mind",
    elements: {
      0: { symbol: "Tl", name: "Talio", group: "Metal del bloque p", desc: "Metal blando que se oxida rápidamente, históricamente usado como veneno.", model: "./models/81Tl.glb" },
      1: { symbol: "Pb", name: "Plomo", group: "Metal del bloque p", desc: "Metal pesado altamente denso, eficaz barrera contra las radiaciones.", model: "./models/82Pb.glb" },
      2: { symbol: "Bi", name: "Bismuto", group: "Metal del bloque p", desc: "El metal con mayor diamagnetismo, compuesto base de antiácidos estomacales.", model: "./models/83Bi.glb" },
      3: { symbol: "Po", name: "Polonio", group: "Metaloide", desc: "Elemento radiactivo extremadamente volátil y altamente peligroso.", model: "./models/84Po.glb" },
      4: { symbol: "At", name: "Astato", group: "Halógeno", desc: "El elemento natural más raro de la corteza terrestre, altamente radiactivo.", model: "./models/85At.glb" },
      5: { symbol: "Rn", name: "Radón", group: "Gas Noble", desc: "Gas noble radiactivo e incoloro generado por la desintegración del radio.", model: "./models/86Rn.glb" },
      6: { symbol: "Fr", name: "Francio", group: "Metal Alcalino", desc: "Metal alcalino inestable del cual solo existen trazas en la naturaleza.", model: "./models/87Fr.glb" },
      7: { symbol: "Ra", name: "Radio", group: "Metal Alcalinotérreo", desc: "Descubierto por Marie Curie, intensamente radiactivo y luminiscente.", model: "./models/88Ra.glb" },
      8: { symbol: "Ac", name: "Actinio", group: "Actínido", desc: "Metal radiactivo que brilla en la oscuridad con una luz azulada.", model: "./models/89Ac.glb" },
      9: { symbol: "Th", name: "Torio", group: "Actínido", desc: "Metal radiactivo considerado una alternativa limpia al uranio nuclear.", model: "./models/90Th.glb" },
      10: { symbol: "Pa", name: "Protactinio", group: "Actínido", desc: "Elemento radiactivo denso, altamente tóxico y subproducto del uranio.", model: "./models/91Pa.glb" },
      11: { symbol: "U", name: "Uranio", group: "Actínido", desc: "Metal pesado reactivo, combustible principal de centrales nucleares.", model: "./models/92U.glb" },
      12: { symbol: "Np", name: "Neptunio", group: "Actínido", desc: "Primer elemento transuránico sintético producido en reactores.", model: "./models/93Np.glb" },
      13: { symbol: "Pu", name: "Plutonio", group: "Actínido", desc: "Elemento fisible artificial utilizado en armas y sondas espaciales.", model: "./models/94Pu.glb" },
      14: { symbol: "Am", name: "Americio", group: "Actínido", desc: "Elemento artificial utilizado comúnmente en detectores de humo domésticos.", model: "./models/95Am.glb" },
      15: { symbol: "Cm", name: "Curio", group: "Actínido", desc: "Sintetizado bombardeando plutonio, usado en espectrómetros espaciales.", model: "./models/96Cm.glb" },
      16: { symbol: "Bk", name: "Berkelio", group: "Actínido", desc: "Actínido sintético nombrado en honor a la Universidad de Berkeley.", model: "./models/97Bk.glb" },
      17: { symbol: "Cf", name: "Californio", group: "Actínido", desc: "Potente emisor de neutrones, usado para iniciar reactores nucleares.", model: "./models/98Cf.glb" },
      18: { symbol: "Es", name: "Einstenio", group: "Actínido", desc: "Identificado en los restos de la primera explosión de bomba de hidrógeno.", model: "./models/99Es.glb" },
      19: { symbol: "Fm", name: "Fermio", group: "Actínido", desc: "Elemento sintético pesado, nombrado en honor al físico Enrico Fermi.", model: "./models/100Fm.glb" },
      20: { symbol: "Md", name: "Mendelevio", group: "Actínido", desc: "Actínido sintético nombrado en reconocimiento a Dmitri Mendeléyev.", model: "./models/101Md.glb" },
      21: { symbol: "No", name: "Nobelio", group: "Actínido", desc: "Elemento radiactivo sintético nombrado en honor a Alfred Nobel.", model: "./models/102No.glb" },
      22: { symbol: "Lr", name: "Lawrencio", group: "Actínido", desc: "Último elemento de la serie de los actínidos, altamente inestable.", model: "./models/103Lr.glb" },
      23: { symbol: "Rf", name: "Rutherfordio", group: "Transactínido", desc: "Primer elemento transactínido sintético con vida media de pocos segundos.", model: "./models/104Rf.glb" },
      24: { symbol: "Db", name: "Dubnio", group: "Transactínido", desc: "Elemento superpesado sintético, producido por colisión de átomos.", model: "./models/105Db.glb" },
      25: { symbol: "Sg", name: "Seaborgio", group: "Transactínido", desc: "Elemento radiactivo artificial cuyos isótopos tienen vidas medias ínfimas.", model: "./models/106Sg.glb" },
      26: { symbol: "Bh", name: "Bohrio", group: "Transactínido", desc: "Nombrado en honor a Niels Bohr, decae rápidamente por emisión alfa.", model: "./models/107Bh.glb" },
      27: { symbol: "Hs", name: "Hassio", group: "Transactínido", desc: "Elemento sintético superpesado cuyo isótopo más estable dura 16 segundos.", model: "./models/108Hs.glb" },
      28: { symbol: "Mt", name: "Meitnerio", group: "Transactínido", desc: "Nombrado en honor a la física Lise Meitner, puramente sintético.", model: "./models/109Mt.glb" },
      29: { symbol: "Ds", name: "Darmstatio", group: "Transactínido", desc: "Elemento sintético creado por fusión nuclear de níquel y plomo.", model: "./models/110Ds.glb" },
      30: { symbol: "Rg", name: "Roentgenio", group: "Transactínido", desc: "Nombrado en honor al descubridor de los rayos X, Wilhelm Röntgen.", model: "./models/111Rg.glb" },
      31: { symbol: "Cn", name: "Copernicio", group: "Transactínido", desc: "Elemento superpesado inestable, nombrado en honor a Nicolás Copérnico.", model: "./models/112Cn.glb" },
      32: { symbol: "Nh", name: "Nihonio", group: "Transactínido", desc: "Primer elemento sintético descubierto y nombrado oficialmente en Asia (Japón).", model: "./models/113Nh.glb" },
      33: { symbol: "Fl", name: "Flerovio", group: "Transactínido", desc: "Elemento radiactivo artificial superpesado, descubierto en Dubná, Rusia.", model: "./models/114Fl.glb" },
      34: { symbol: "Mc", name: "Moscovio", group: "Transactínido", desc: "Elemento sintético inestable, extremadamente difícil de producir.", model: "./models/115Mc.glb" },
      35: { symbol: "Lv", name: "Livermorio", group: "Transactínido", desc: "Elemento transactínido obtenido por bombardeo de curio con calcio.", model: "./models/116Lv.glb" },
      36: { symbol: "Ts", name: "Tenesino", group: "Transactínido", desc: "El segundo elemento más pesado creado artificialmente en la actualidad.", model: "./models/117Ts.glb" },
      37: { symbol: "Og", name: "Oganesón", group: "Transactínido", desc: "El elemento de mayor número atómico y masa sintética conocido por la ciencia.", model: "./models/118Og.glb" }
    }
  }
];